#! /bin/sh
sxhkd &
polybar bar &
picom &
dunst &
flameshot &
feh --bg-fill media/images/wallpaper-base16.png

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           10

# others
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true

bspc config normal_border_color   "#282828"
bspc config active_border_color	  "#282828"
bspc config focused_border_color  "#282828"
bspc config urgent_border_color   "#282828"
