#! /bin/sh
sxhkd &
picom &
dunst &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bscp config window_gap           10

# others
bscp config split_ratio           0.50
bscp config borderless_monocle    true
bscp config gapless_monocle       false
bscp config focus_follows_pointer true

bscp config normal_border_color   "#282828"
bscp config active_border_color	  "#282828"
bscp config focused_border_color  "#383838"
bscp config urgent_border_color   "#ab4642"
